# 股票交易计划

## 前言

在股票交易中，如何让自己的投资策略不随市场的情绪而波动
唯一的办法，就是

1. 建立自己的投资计划
2. 并坚持投资纪律
3. 耐心等待

今天我们就如何构建投资计划，开始一段用python程序来代替人来做决策，
从而控制自己的手

In [2]:
import pandas as pd

## 投资计划函数

In [4]:
# 自定义函数，针对单个标的的投资计划

def plan(name,price_init,rate_init,shares_init,data):
    df = pd.DataFrame(data=data)
    df['加仓批次'] = list(range(1,len(df)+1))
    df['名称'] = name
    df['价格'] = df['价格系数'] * price_init
    df['shares'] = ''
    df['money'] = ''    
    print(df)
    df.loc[df['加仓批次']==1, 'shares'] = shares_init
    print(df)
    df.loc[df['加仓批次']==1, 'money'] = df.loc[df['加仓批次']==1, '价格'] * df.loc[df['加仓批次']==1, 'shares']
    money_init = df.loc[df['加仓批次']==1, 'money'].values[0]  
    for i in range(len(df)-1):
        n = i+2   
        df.loc[df['加仓批次']==n, 'shares'] = round(money_init*df.loc[df['加仓批次']==n, '加仓比例']/\
                                                (rate_init * df.loc[df['加仓批次']==n, '价格']*100),0)*100
        df.loc[df['加仓批次']==n, 'money'] = df.loc[df['加仓批次']==n, '价格'] * df.loc[df['加仓批次']==n, 'shares']
    
    df['累计仓位'] = df['加仓比例'].cumsum()
    df['累计份额'] = df['shares'].cumsum()
    df['累计金额'] = df['money'].cumsum()
    df['成本'] = df['累计金额']/df['累计份额']
    df['下跌幅度'] = 1- df['价格系数']
    df['下跌幅度'] = df['下跌幅度'].apply(lambda x:f'下跌{int(round(x*100,0))}%')
    df.loc[df['加仓批次']==1, '下跌幅度'] = '首次'
    df = df[['名称','加仓批次', '下跌幅度', '价格系数','价格', '加仓比例', '累计仓位', 
             'shares', 'money','累计份额', '累计金额','成本']]
    return df

## 中概互联

In [5]:
# 标的名称
name = '中概互联-513050'

# 首次购入价格
price_init = 2.0

# 首次加仓比例
rate_init = 0.01

# 首次购入份额数量
shares_init = 2000

data = {
    '价格系数':[1,0.95,0.9,0.85,0.8,0.75,0.7,0.65],
    '加仓比例':[rate_init,0.02,0.03,0.04,0.05,0.05,0.05,0.05],
    }
df = plan(name,price_init,rate_init,shares_init,data)

format_dict = {'money': '￥{0:.0f}', 
               '累计金额': '￥{0:.0f}', 
               '价格': '{0:.3f}', 
               '成本': '{0:.3f}', 
               'shares': '{0:.0f}', 
               '累计份额': '{0:.0f}', 
               '价格系数': '{0:.0%}', 
               '加仓比例': '{0:.2%}', 
               '累计仓位': '{0:.2%}', 
                }
# print(name)
df.style.hide_index().format(format_dict)

## 万科

In [6]:
# 标的名称
name = '万科'

# 首次购入价格
price_init = 22

# 首次加仓比例
rate_init = 0.01

# 首次购入份额数量
shares_init = 300

data = {
    '价格系数':[1,0.95,0.9,0.85,0.8,0.75,0.7,0.65],
    '加仓比例':[rate_init,0.02,0.03,0.04,0.05,0.05,0.05,0.05],
    }
df = plan(name,price_init,rate_init,shares_init,data)

format_dict = {'money': '￥{0:.0f}', 
               '累计金额': '￥{0:.0f}', 
               '价格': '{0:.3f}', 
               '成本': '{0:.3f}', 
               'shares': '{0:.0f}', 
               '累计份额': '{0:.0f}', 
               '价格系数': '{0:.0%}', 
               '加仓比例': '{0:.2%}', 
               '累计仓位': '{0:.2%}', 
                }
df.style.hide_index().format(format_dict)

   价格系数  加仓比例  加仓批次  名称    价格 shares money
0  1.00  0.01     1  万科  22.0
1  0.95  0.02     2  万科  20.9
2  0.90  0.03     3  万科  19.8
3  0.85  0.04     4  万科  18.7
4  0.80  0.05     5  万科  17.6
5  0.75  0.05     6  万科  16.5
6  0.70  0.05     7  万科  15.4
7  0.65  0.05     8  万科  14.3
   价格系数  加仓比例  加仓批次  名称    价格 shares money
0  1.00  0.01     1  万科  22.0    300
1  0.95  0.02     2  万科  20.9
2  0.90  0.03     3  万科  19.8
3  0.85  0.04     4  万科  18.7
4  0.80  0.05     5  万科  17.6
5  0.75  0.05     6  万科  16.5
6  0.70  0.05     7  万科  15.4
7  0.65  0.05     8  万科  14.3